### ISSUE TITLE
Road Map For Me

### ISSUE THREAD

**Issue by Jashpatel7** [Jashpatel7/coursera_web#2]
- [ ] Learn Git and Github
- [ ] HTML, CSS, Javascript(Basic, Core, Angularjs, Reactjs)
- [ ] jQuery and AJAX
- [ ] Django Framework (Optional)
@**Jashpatel7** First Do This.....
